default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV["DATABASE_URL_TEST"] || "postgres://postgres:postgres@db:5432/rails_api_demo_test" %>

production:
  <<: *default